Add music and fix typo
AntoninLoubiere/hanamikoji-site pull request #93
Opened 2023-08-22 20:04 UTC by Triw-12

ça marche comme ça ?

2023-08-22 20:06 UTC, Triw-12 commented
Ajouter un bouton couper le son/le remettre si c'est ok

2023-08-23 08:46 UTC, AntoninLoubiere requested changes

2023-08-23 08:46 UTC, AntoninLoubiere commented on website/static/play/play.js
> +    let audio = new Audio("bell-me.mp3");
```suggestion
    let audio = new Audio("/static/play/bell-me.mp3");
```
L'URL devrait être absolue (car on a déplacé le fichier play (maintenant c'est /play))

2023-08-23 08:49 UTC, AntoninLoubiere approved these changes

2023-08-23 09:33 UTC, merged